import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Layout from '../components/Layout';
import UploadBox from '../components/UploadBox';
import AssetList from '../components/AssetList';
import AnalysisStatus from '../components/AnalysisStatus';
import RequirementInput from '../components/RequirementInput';
import { addMessage, analyzeProject, getMessages, getProject, getReports } from '../api/projects';
import { analyzeAsset, getAssets, uploadAsset } from '../api/assets';
import type { AnalysisResult, Asset, Message, Project, Report } from '../types';
export default function ProjectDetailPage(){const id=Number(useParams().id);const [project,setProject]=useState<Project>();const [assets,setAssets]=useState<Asset[]>([]);const [reports,setReports]=useState<Report[]>([]);const [messages,setMessages]=useState<Message[]>([]);const [analysis,setAnalysis]=useState<AnalysisResult[]>([]);const [busyAsset,setBusyAsset]=useState<number>();const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);
 const refresh=async()=>{setProject(await getProject(id));setAssets(await getAssets(id));setReports(await getReports(id));setMessages(await getMessages(id));};useEffect(()=>{refresh()},[id]);
 return <Layout>{project&&<><div className="grid gap-4 md:grid-cols-[1fr_260px]"><section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{project.title}</h1><p className="mt-2 text-slate-600">{project.description}</p><p className="mt-3 text-sm text-slate-500">项目类型：{project.project_type}</p></div><button disabled={busy} onClick={async()=>{setBusy(true);try{const rs=await analyzeProject(id);setReports(rs);await refresh();}finally{setBusy(false);}}} className="rounded-xl bg-green-600 px-4 py-2 text-white disabled:opacity-60">{busy?'综合分析中...':'综合分析项目'}</button></div></section><AnalysisStatus status={project.status} score={project.requirement_score}/></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr]"><div className="space-y-6"><RequirementInput onSubmit={async(text)=>{await addMessage(id,text);await refresh();}}/><UploadBox loading={uploading} onUpload={async(file)=>{setUploading(true);try{await uploadAsset(id,file);await refresh();}finally{setUploading(false);}}}/><section><h2 className="mb-3 font-semibold">已上传资料</h2><AssetList assets={assets} busyId={busyAsset} onAnalyze={async(assetId)=>{setBusyAsset(assetId);try{const res=await analyzeAsset(assetId);setAnalysis(prev=>[res,...prev]);await refresh();}finally{setBusyAsset(undefined);}}}/></section></div>
 <div className="space-y-6"><section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-semibold">补充需求记录</h2><div className="mt-3 max-h-52 space-y-2 overflow-auto">{messages.map(m=><p key={m.id} className="rounded-lg bg-slate-50 p-2 text-sm">{m.content}</p>)}</div></section><section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-semibold">本次资料分析结果</h2><div className="mt-3 space-y-3">{analysis.map(a=><div key={a.id} className="rounded-lg bg-slate-50 p-3 text-sm"><div className="font-medium">{a.analyzer_type}</div><pre className="mt-2 max-h-40 whitespace-pre-wrap overflow-auto text-xs text-slate-600">{a.summary}</pre></div>)}</div></section><section className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold">报告列表</h2><button disabled={busy} onClick={async()=>{setBusy(true);try{const rs=await analyzeProject(id);setReports(rs);await refresh();}finally{setBusy(false);}}} className="text-sm text-blue-600">生成文档</button></div><div className="mt-3 space-y-2">{reports.map(r=><Link key={r.id} to={`/reports/${r.id}`} className="block rounded-lg border p-3 hover:bg-slate-50"><div className="font-medium">{r.title}</div><div className="text-xs text-slate-500">{r.report_type}</div></Link>)}</div></section></div></div></>}</Layout>}
