import {apiClient} from './client';import type {WorkGroup,WorkGroupMessage,WorkGroupMember} from '../types';
export const getWorkGroups=async()=> (await apiClient.get<WorkGroup[]>('/work-groups')).data;
export const createWorkGroup=async(data:any)=>(await apiClient.post<WorkGroup>('/work-groups',data)).data;
export const getWorkGroup=async(id:number)=>(await apiClient.get<WorkGroup>(`/work-groups/${id}`)).data;
export const updateWorkGroup=async(id:number,data:any)=>(await apiClient.put<WorkGroup>(`/work-groups/${id}`,data)).data;
export const getGroupMembers=async(id:number)=>(await apiClient.get<WorkGroupMember[]>(`/work-groups/${id}/members`)).data;
export const addGroupMembers=(id:number,employee_ids:number[])=>apiClient.post(`/work-groups/${id}/members`,{employee_ids});
export const removeGroupMember=(id:number,eid:number)=>apiClient.delete(`/work-groups/${id}/members/${eid}`);
export const getGroupMessages=async(id:number)=>(await apiClient.get<WorkGroupMessage[]>(`/work-groups/${id}/messages`)).data;
export const sendGroupMessage=(id:number,content:string)=>apiClient.post(`/work-groups/${id}/messages`,{content});
export const clearGroupMessages=(id:number)=>apiClient.delete(`/work-groups/${id}/messages`);
export const startAutoOperation=async(id:number)=>(await apiClient.post(`/works/${id}/auto-operation/start`)).data;
export const getAutoStatus=async(id:number)=>(await apiClient.get(`/works/${id}/auto-operation/status`)).data;
